# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosttable',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
