# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoststate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('cpustate', models.CharField(max_length=50)),
                ('memstate', models.CharField(max_length=50)),
                ('intersent', models.CharField(max_length=50)),
                ('interrecv', models.CharField(max_length=50)),
                ('dateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
