# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_hoststate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoststate',
            name='cpustate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hoststate',
            name='interrecv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hoststate',
            name='intersent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hoststate',
            name='memstate',
            field=models.IntegerField(),
        ),
    ]
