# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0003_hosttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosttable',
            old_name='hostcpuhdd',
            new_name='hosthdd',
        ),
    ]
