# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0004_auto_20170712_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosttable',
            name='hostcpu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hosttable',
            name='hosthdd',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hosttable',
            name='hostmem',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hosttable',
            name='hostname',
            field=models.CharField(max_length=50),
        ),
    ]
