# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0005_auto_20170712_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosttable',
            name='hostip',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
