# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0006_hosttable_hostip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosttable',
            name='hostip',
            field=models.GenericIPAddressField(),
        ),
    ]
